### ISSUE TITLE
add franchise field to anime and manga

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#1467]

**Comment by SpaceShipTerra** [comment]
#1467 дублирует
https://github.com/shikimori/shikimori/issues/1062

Чтобы далеко не ходить, ниже два дубля друг друга:
https://github.com/shikimori/shikimori/issues/559
https://github.com/shikimori/shikimori/issues/343

И ещё. Тут уже не уверен, но очень похоже, что три раза про одно и то же:
https://github.com/shikimori/shikimori/issues/1420
https://github.com/shikimori/shikimori/issues/444
https://github.com/shikimori/shikimori/issues/337

**Comment by morr** [comment]
@SpaceShipTerra спасибо! Закрыл дубли.
