### ISSUE TITLE
Rich link preview support for news forum links

### ISSUE THREAD

**Issue by enchained** [shikimori/shikimori#1468]
https://medium.com/@richardoosterhof/how-to-optimize-your-site-for-rich-previews-527ed13a6d69

**Comment by morr** [comment]
@enchained I already added open graph meta tags to the site few months ago

**Comment by enchained** [comment]
@morr Yes, I think it works for the most pages, but not for things like:
https://shikimori.org/forum/animanga/245029-stali-izvestny-nazvanie-syuzhet-i-data-premiery-filma-moya-geroyskaya-akademiya

Preview for such links doesn't appear for me at all, just the link itself, not even the page title. Tested in telegram. Also it doesn't pass the preview tags tests here: https://richpreview.com so maybe we are talking about two different things.
