### ISSUE TITLE
Latest updates

### ISSUE THREAD

**Issue by imKota** [shikimori/shikimori#1480]
@morr Please add to the api methods to get the latest added/modified anime/manga/ranobe/characters/people/

Example:

```
https://shikimori.org/api/v2/updates?type=animes&kind=tv&limit=5
https://shikimori.org/api/v2/updates?type=manga&kind=doujin&limit=20
https://shikimori.org/api/v2/updates?type=ranobe&limit=15
https://shikimori.org/api/v2/updates?type=characters&limit=13
https://shikimori.org/api/v2/updates?type=people&limit=10
```

**Comment by morr** [comment]
@imKota i can't do it. `anime/manga/ranobe/characters/people` models do not have a field where the date of the last change of its fields is stored

`updated_at` field in `anime/manga/ranobe/characters/people` is used for another purposes. this field is changed every time when any of related wtith `anime/manga/ranobe/characters/people` models are updated.
