### ISSUE TITLE
xss in clubs

### ISSUE THREAD

**Issue by Aesthesys** [shikimori/shikimori#1533]
Привет, нашел xss в интерфейсе клубов, пейлоад указал ниже, вставляется в название клуба, эксплойтится при входе-выходе из него из за вот этого [алерта](https://i.imgur.com/wne4zDQ.png):

`<img src="https://dere.shikimori.org/system/users/x160/115289.png" onload="alert(1)">`

**Comment by Aesthesys** [comment]
@morr

**Comment by morr** [comment]
@Aesthesys прости за поздний ответ, issue затерялась среди кучи других. Исправлено :)
