### ISSUE TITLE
proposal: user-defined JavaScript

### ISSUE THREAD

**Issue by tie** [shikimori/shikimori#1556]
## Introduction: User-Scripts
Mature desktop browsers support extensions.  At least Chrome, Safari, and Firefox have the so-called *user-script* extensions.  Those allow execution of locally-stored JavaScript code on the websites.  The same goes for the CSS *user styles*.  However, shikimori supports and hosts user-defined styles.  Beyond the obvious user page personalization, it enables the consistent experience among all the user's devices and browsers.  Moreover, mobile versions of the former browsers are not extensible.

## Proposal
Shikimori's interface can be *personalized* using the custom stylesheets.  I propose adding the support for user-defined JavaScript scenarios to *extend and enhance the functionality* of the service.

## Brief Design

- Only users may define scripts.
- User's script is editable through the user's Site Appearance settings.  That is, in a manner similar to editing Site Styles.
- The script uploaded by the user should be executed *if and only if* this particular user is logged in.
- The script is executed on the another user's or club's page only if site appearance customization ("Apply user styles" option in Site Appearance) is disabled to avoid messing up the page — some scripts may modify DOM on a wrong assumption of an element appearance.

### Privacy Concerns
Serving custom script implies that the server will send an arbitrary code to the user's browser.  The script should only be served for the script owner to protect innocent users from a potential attack surface.  I'd also warn users in the preferences to use third-party scripts only if they trust the source.

## Beneficiaries

There are numerous extensions for shikimori implemented as browser extensions or user-scripts, e.g. [IHeardYouLikeLicense](https://github.com/SebyakinAndrei/IHeardYouLikeLicense) (written by @SebyakinAndrei), [shikimori-userscripts](https://github.com/Seryiza/shikimori-userscripts) (by @Seryiza) and [shiki extender](https://openuserjs.org/scripts/Newt300/shiki_UI_extender) by [SThorn](https://shikimori.org/SThorn).

## JavaScript in the Wild
- [wikipedia.org](https://wikipedia.org) supports both user-defined CSS and JavaScript code.
- Anime wikis (like MAL) allow CSS, but as far as I know, none of them support user-defined JavaScript.

**Comment by tie** [comment]
Also, there is a [dedicated page for user scripts][1] in CSS-club.

[1]: https://shikimori.org/clubs/811-css-club-nastroyka-vneshnego-vida-sayta/pages/264-polzovatelskie-skripty

**Comment by morr** [comment]
@tie I implemented the customisation of styles so that other users could see them. As you mentioned in this proposal, user scripts are not safe to make them available for all users, they are safe for their owners only.
But users who want to customised scripts (and who have skills to write their own scripts) can already use them with browser extensions like greasemonkey. 

In summary: I don't want to implement a feature which will have effect for only "current" user, especially if there are alternatives in browser extensions.

**Comment by Tirraon** [comment]
@morr Mobile browsers mostly don't support user scripts. 
But I agree, that it isn't really needed.
Better to implement some scripts from [club](https://shikimori.org/clubs/811-css-club-nastroyka-vneshnego-vida-sayta/pages/264-polzovatelskie-skripty) as optional site functionality (for example, real shiki rating).

**Comment by tie** [comment]
@morr

>a feature which will have effect for only "current" user

That's how custom styles are working right now on the whole website if the owner/user is logged in.  Or is just an extra feature because style customization was worth implementing in the first place?

Scripts could be embedded into the page DOM by the browser extension but as @Tirraon mention above mobile browsers mostly don't support user scripts.

While I agree that user-defined scripts are not really needed, there is definitely a high demand for such feature from script developers.  One of the possible applications is passing the responsibility for copyright infringement to the third-party.  That is, to the script developer.

For example, the developer of [IHeardYouLikeLicense](https://github.com/SebyakinAndrei/IHeardYouLikeLicense) is running an API that implements the functionality for mimicking a regular play.shikimori.org page — that's how his extension works.  Of course, in that particular case, the scripts *must not* be stored on the shikimori server but rather referenced by the *src* attribute of the *script* tag to comply with the copyright laws on the shikimori's side.

**Comment by tie** [comment]
@Tirraon
>Better to implement some scripts as optional site functionality (for example, real shiki rating)

Yeah, the [real shikimori rating](https://shikimori.org/forum/site/218886-shiki-reyting-introdyusing-nyu-kul-ficha) is a long-awaited feature.
