### ISSUE TITLE
HTTP 500 in account settings

### ISSUE THREAD

**Issue by tie** [shikimori/shikimori#1577]
- Steps to reproduce:
  * Login.
  * Go to the account account settings page.
  * Clear __user_nickname__ input field.
  * Paste *[U+2063 INVISIBLE SEPARATOR](https://unicode-table.com/en/2063/)* or *[U+200B ZERO WIDTH SPACE](https://unicode-table.com/en/200B/)* into the __user_nickname__ input field.
  Probably some other Unicode characters will cause HTTP 500 status code too.
  * Click __Save__ button.
- Expected results:
  * shikimori updates the nickname or at least reports that the character is not allowed.
- Actual results:
  * HTTP server error status code and redirect to user's profile page.

<p align=center><img src="https://shikimori.org/images/static/503.jpg" alt="HTTP 503 status code anime-style art">

**Comment by morr** [comment]
@tie fixed. thanks!

**Comment by tie** [comment]
OK, thank you!
