### ISSUE TITLE
support for video hosting viuly.io

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#1645]
https://viuly.io/embed/0148--neveroyatnoe-priklyuchenie-dzhodzho-rycari-zvzdnoy-pyli--anidub-150196

**Comment by Lambda1Elite** [comment]
Тэг **iframe** для frontend-а.
><iframe src="https://viuly.io/embed/0148--neveroyatnoe-priklyuchenie-dzhodzho-rycari-zvzdnoy-pyli-->anidub-150196" frameborder="0" width="600" height="400" allowfullscreen></iframe>
