### ISSUE TITLE
History back on Chrome Andriod doesn't work

### ISSUE THREAD

**Issue by NogrTL** [shikimori/shikimori#1670]
При действии назад в Chrome браузере на Andriod`е прошлая страница не отображается.

К сожелению, я не смог выяснить внятной причины из Remote debbuger`а

**Comment by morr** [comment]
@NogrTL, какая версия Android?
 у меня к сожалению нет ни одного устройства на андроиде, поэтому вряд ли смогу что-то исправить, не имея возможности воспроизвести проблему.

есть шанс, что эта проблема исправлена в обновлённой версии https://github.com/turbolinks/turbolinks , обновление с апгрейдом турболинков я выложу уже скоро, в течении недели-двух

**Comment by NogrTL** [comment]
У меня повторялось на версиях от 6 до 9.
И на Firefox я такого не наблюдал так что думал это такая-то специфическая проблема Chrom`а

**Comment by NogrTL** [comment]
Проблема продолжает появляться.
Я выловил ошибку с Android девайса.

[shikimori.org-1568825376393.log](https://github.com/shikimori/shikimori/files/3627562/shikimori.org-1568825376393.log)

На моей территории часть ресурсов России заблокировано(в том числе Яндекса и Мейл.ру).
Из-за этого похоже некоторые скрипты не грузятся и вызывают ошибку.
