### ISSUE TITLE
old & duplicate issues

### ISSUE THREAD

**Issue by Tsuchimikado** [shikimori/shikimori#1714]
**Устаревшие**:
- [аниме в виде картинок в списке](https://github.com/shikimori/shikimori/issues/195) - реализовано https://shikimori.org/morr/list/anime/order-by/name
- [отображение в комментарии ссылки на ответы на комментарий](https://github.com/shikimori/shikimori/issues/265) - реализовано https://shikimori.org/morr/comments
- [хентайные треды помечать как 18+](https://github.com/shikimori/shikimori/issues/274) - реализовано (?)
- [франшизы аниме и манги](https://github.com/shikimori/shikimori/issues/327) - реализовано https://shikimori.org/animes/6746-durarara/franchise
- [Возможность редактировать картинки аниме, манги, персонажей и людей (новая редактируемая сущность для постеров)](https://github.com/shikimori/shikimori/issues/573) - реализовано https://shikimori.org/animes/205-samurai-champloo/edit
- [Переработка меню](https://github.com/shikimori/shikimori/issues/669) - устарело
- [Переработка поиска. Большое поле. Результаты внизу в отдельном блоке контента](https://github.com/shikimori/shikimori/issues/716) - реализовано https://shikimori.org/
- [На главной внизу после новостей ссылка на продолжение](https://github.com/shikimori/shikimori/issues/732) - устарело [main page remake](https://github.com/shikimori/shikimori/issues/1711)
- [replace copyrighted posters for animes](https://github.com/shikimori/shikimori/issues/755) - устарело (?)
- [удалить все связи с world-art](https://github.com/shikimori/shikimori/issues/902) - устарело (?)
- [бб код для двухколоночной вёрстки](https://github.com/shikimori/shikimori/issues/1049) - реализовано [div=cc-2][div=cc-2a][div=c-column]
- [оповещение о выходе серии приходит до модерации (хотя раньше приходила только после принятия видео).](https://github.com/shikimori/shikimori/issues/1663) - устарело https://shikimori.org/forum/site/284415-onlayn-prosmotr
- [create episode notification after video is moderated](https://github.com/shikimori/shikimori/issues/1691) - устарело https://shikimori.org/forum/site/284415-onlayn-prosmotr

**Дубли**:
- [Настройка для получения уведомлений о хентае](https://github.com/shikimori/shikimori/issues/594)
[галочка для получения уведомлений о 18+ аниме](https://github.com/shikimori/shikimori/issues/653)

- [realtime уведомеление о появлении нового личного сообщения](https://github.com/shikimori/shikimori/issues/343)
[reatime mail & notifications](https://github.com/shikimori/shikimori/issues/898)

- [попробовать сделать выключение топиков об эпизодах](https://github.com/shikimori/shikimori/issues/901)
[add option to disable visibility of episode topics on forum. remove report-spoiler-button for comments of such topics. ](https://github.com/shikimori/shikimori/issues/1650)

- [articles](https://github.com/shikimori/shikimori/issues/1590)
[articles](https://github.com/shikimori/shikimori/issues/1710)

**Можно обьединить**:
- [для новости анонса дополнительная пометка о том, что это анонс продолжения для аниме, которое пользователь уже просмотрел](https://github.com/shikimori/shikimori/issues/286)
[Cделать так что если уже аниме брошено и отложено чтобы новости по новому сезону, выходу новой серии, овашки и тому подобному не приходили так как это уже не интересует](https://github.com/shikimori/shikimori/issues/468)
[Категории новостей. Уведомления о новостях. Уведомления только о категориях, на которые пользователь подписан.](https://github.com/shikimori/shikimori/issues/1026)
[получение уведомлений об анонсе/онгоинге/релизе аниме, связанного с находящимся в списке пользователя](https://github.com/shikimori/shikimori/issues/1225)
[добавить кнопку "эпизод просмотрен" или вроде того в новостях о выходе серии](https://github.com/shikimori/shikimori/issues/1275)
[notify users when related anime is added to db](https://github.com/shikimori/shikimori/issues/1618)

- [После регистрации слать не только уведомление, но и кидать на специальную страницу с текстом тоже самого сообщения. В сообщение добавить ссылку на топик приветствия.](https://github.com/shikimori/shikimori/issues/717)
[страница после регистрации. на странице можно сделать импорт, можно искать аниме/мангу и добавлять их в свой список](https://github.com/shikimori/shikimori/issues/1355)

**Comment by morr** [comment]
@Tsuchimikado спасибо! Позакрывал лишнее. Авгиевы конюшни стали чуть чище :)
