### ISSUE TITLE
Предложение: возможность указывать высоту и ширину для постеров

### ISSUE THREAD

**Issue by cawa-93** [shikimori/shikimori#1730]
https://github.com/shikimori/shikimori/blob/96253147c14ede539bcc811697fd884211918067/app/services/bb_codes/tags/poster_tag.rb#L8-L14

Иногда изображение очень не пропорционально. И оно слишком увеличивается. Хочется указать максимальную высоту или максимальную ширину, чтобы постер не превышал этих размеров

**Comment by morr** [comment]
@cawa-93 приведи, пожалуста, пример неправильно масштабирующейся картинки

**Comment by cawa-93** [comment]
Ну, Как пример — https://shikimori.org/clubs/2423-demo-club

Картинка масштабируется правильно. Она пытается растянуться на всю ширину страниицы. Тут все ок.

Я рассматриваю [poster] как способ разместить в клубе не кликабельное изображение, чисто для красивого оформления. Чтобы оно не попадало в галерею вместе с другими изображениями. 

Хочется как в теге [img] иметь возможность управлять его размером. Но такой нет. А если использовать сам [img] тогда картинка становиться кликабельной и её можно открыть в галерее.

**Comment by morr** [comment]
@cawa-93 а если для img тега добавить параметр, отключающий превращение картинки в картинку галлереи? тогда твоя проблема будет решена?

**Comment by cawa-93** [comment]
Думаю да.

**Comment by morr** [comment]
@cawa-93 https://shikimori.one/bb_codes
![image](https://user-images.githubusercontent.com/134610/61371540-9b478c00-a89d-11e9-8229-70ca6c9ae4bc.png)
