### ISSUE TITLE
Почему игнорируемые пользователем топики и сообщения не отфильтровываються на сервере?

### ISSUE THREAD

**Issue by cawa-93** [shikimori/shikimori#1754]
Иногда на форуме не загружается ничего:

![image](https://user-images.githubusercontent.com/1662812/64245632-f6981100-cf13-11e9-96ee-c7824163c1d7.png)

Попытался розобраться в причине. Дело в вот в чем:
С сервера приходит первая партия топиков. Но все они находяться у меня у "Игноре". И как следствие все они удаляються. И не отображаеться ничего. Клиент загрузил 8 топиков зря — бесполезный трафик.

Я дергаю стколл, и загружаеться следующая партия топиков, но среди них только два не в игноре. В результате отображаеться только два топика, а не 8 как положено. Клиент загрузил 6 топиков зря — бесполезный трафик.
![image](https://user-images.githubusercontent.com/1662812/64246282-357a9680-cf15-11e9-973c-93f460113311.png)

Как я понимаю с загрузкой комментариев тот же принцип: с сервера загружаються все, а игнорируемые пользователи удаляються уже на клиенте.

Разве не логичнее было бы отфильтровывать игнорируемые топики и сообщения на сервере при выборе из БД?

**Comment by morr** [comment]
@cawa-93 потому, что фильтрация на сервере ломает кеширование

вот что кеширует сервер
![image](https://user-images.githubusercontent.com/134610/64488035-4b58c600-d24b-11e9-8e0f-e841fe3a3ec9.png)

если сделать игнор топиков на уровне сервера, то не будет работать самое верхнее кеширование (красный цвет)
если сделать игнор комментов на уровне сервера, то не будет работать кеш на уровне комментов (зеленый цвет) что автоматически сделает не рабочим и все кеши более верхнего уровня
