### ISSUE TITLE
Возможность скрывать из манга/аниме списков определенные элементы или жанры

### ISSUE THREAD

**Issue by maxkatz6** [shikimori/shikimori#1857]
@morr 
Планируется ли возможность скрывать из манга/аниме списков определенные элементы или жанры?
Списки удобны для организации просмотренного/прочитанного, но не все есть желание выставлять на публику.
Сейчас можно скрыть только весь список полностью.

**Comment by morr** [comment]
@maxkatz6 нет
список пользователя это не только страницы самого списка, но и история, логи, статистика, апи.
программировать фильтрацию всего этого слишком трудоёмко
