### ISSUE TITLE
/api/animes order direction

### ISSUE THREAD

**Issue by Smarthard** [shikimori/shikimori#1907]
Не нашел в [документации](https://shikimori.one/api/doc/1.0/animes/index) параметр для указания порядка, в котором будут выводиться аниме. Как было сказано в [топике](https://shikimori.one/comments/5983073) обсуждения API, в `/api/comments` есть такая возможность с помощью параметра `desc`, в `/api/animes` этот параметр, видимо, не учитывается.

**Comment by morr** [comment]
@Smarthard  `order`
![image](https://user-images.githubusercontent.com/134610/85402430-583d7080-b564-11ea-81a2-758610c24a87.png)

**Comment by Smarthard** [comment]
@morr я имел в виду, можно ли сделать такой запрос, чтобы ответ пришел в обратном порядке.

Пример:

[/api/animes?order=id&desc=1](https://shikimori.one/api/animes?order=id&desc=1) и [/api/animes?order=id&desc=0](https://shikimori.one/api/animes?order=id&desc=0) сейчас возвращают [Ковбоя Бибопа](https://shikimori.one/animes/1-cowboy-bebop)

**Comment by morr** [comment]
@Smarthard нет. обратный порядок выборки в коде не запрограммирован в принципе.
Добавлять её не планирую.

Если очень хочется сортировку, то единственный вариант - закодить её самостоятельно и прислать пулреквест в проект
Сортируется тут
https://github.com/shikimori/shikimori/blob/master/app/query_objects/animes/filters/order_by.rb
https://github.com/shikimori/shikimori/blob/master/spec/query_objects/animes/filters/order_by_spec.rb
Применяется в апи тут
https://github.com/shikimori/shikimori/blob/master/app/controllers/api/v1/animes_controller.rb#L99
https://github.com/shikimori/shikimori/blob/master/app/controllers/api/v1/mangas_controller.rb#L65
https://github.com/shikimori/shikimori/blob/master/app/controllers/api/v1/ranobe_controller.rb#L39
