### ISSUE TITLE
NONE external link does not hide wikipedia

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#1914]
https://shikimori.one/animes/41383-obake-zukan/edit/external_links

**Comment by morr** [comment]
`Сейчас только русскую уберает. Поэтому англ.вики и не изчезает.`

**Comment by grin3671** [comment]
А так нельзя: [#733767](https://shikimori.one/moderations/versions/733767) ?

**Comment by morr** [comment]
@grin3671 мне говорят, что помогло. спасибо!
