### ISSUE TITLE
Email-уведомления о выходе новых серий, завершении показа и т.д

### ISSUE THREAD

**Issue by BogdanJava** [shikimori/shikimori#1937]
На странице аниме тайтла/манги добавить кнопку `Подписаться на уведомления`, которая будет позволять пользователям отслеживать выход продукта в различных вариациях путём отправки email и/или уведомлений на сайте: `завершение показа(полный выход)`, `выход новой серии` и так далее.

**Comment by morr** [comment]
@BogdanJava подписка уже есть для всех аниме находящихся в списке пользователя (кроме статуса "брошено", кажется)
тоесть чтобы подписаться, нужно добавить аниме себе в список

рассылок на емайл не будет. письма сайта шлются только для двух вещей: сброс пароля/уведомление о личном сообщении
