### ISSUE TITLE
Поиск не находит всех персонажей

### ISSUE THREAD

**Issue by SynthesisOne** [shikimori/shikimori#1973]
Если ввести в строку поиска Кляйн не находит персонажа https://shikimori.one/characters/36830-ryoutarou-tsuboi
Возможны похожие проблемы с другими персонажами

**Comment by rnstlange** [comment]
> Если ввести в строку поиска Кляйн не находит персонажа https://shikimori.one/characters/36830-ryoutarou-tsuboi
> Возможны похожие проблемы с другими персонажами

Видимо просто результатов выводится слишком много, поэтому его там нет. Если ввести "Рёта кляйн" то все работает

**Comment by rnstlange** [comment]
При нажатии на Enter он тоже находит
![screenshot](https://user-images.githubusercontent.com/41155721/92573217-fb08af80-f274-11ea-9a28-d094bc4ae0ea.png)

**Comment by SynthesisOne** [comment]
> При нажатии на Enter он тоже находит
> ![screenshot](https://user-images.githubusercontent.com/41155721/92573217-fb08af80-f274-11ea-9a28-d094bc4ae0ea.png)

Да, такое предположил но enter не работал как положено, и отправлял на страницу к конкретному герою на которого была наведена мышка, даже если фокус находится в строке поиска
