### ISSUE TITLE
Not localized hint in settings

### ISSUE THREAD

**Issue by Molkree** [shikimori/shikimori#1985]
![image](https://user-images.githubusercontent.com/12860284/92738258-75742500-f384-11ea-81f3-ddc458e90f88.png)
Hint is written in Russian despite English interface.

**Comment by st0chast** [comment]
![20-01-2022](https://user-images.githubusercontent.com/52094478/150318927-a2318ac7-260b-4ee7-8175-acb031a857fa.png)
the hint is no longer there 🤷

**Comment by Molkree** [comment]
Closing as the hint is no longer present/
