### ISSUE TITLE
Поиск не находит сериал "Oregairu 3" 2020 года

### ISSUE THREAD

**Issue by adem4ik** [shikimori/shikimori#2087]
**Предусловие:** у аниме https://shikimori.one/animes/39547-yahari-ore-no-seishun-love-comedy-wa-machigatteiru-kan в Альтернативных названиях содержится "Oregairu 3"
![Редактирование аниме  Yahari Ore no Seishun Love Comedy wa Machigatteiru  Kan  Аниме - Vivaldi](https://user-images.githubusercontent.com/4707112/99099337-b80be500-25f3-11eb-8bd8-094d0ec11025.jpg)

1. Открыть сайт
2. Ввести в поиск "Oregairu" (либо "Oregairu 3")

**Результат:** В подсказках и в результатах отсутствует https://shikimori.one/animes/39547-yahari-ore-no-seishun-love-comedy-wa-machigatteiru-kan 
![1](https://user-images.githubusercontent.com/4707112/99099078-564b7b00-25f3-11eb-983b-09c34c86437b.jpg)

**Comment by morr** [comment]
@adem4ik потому что только шесть полей из синонимов индексируются
https://github.com/shikimori/shikimori/blob/master/app/chewy/animes_index.rb#L4

Кто же знал, что будет столько синонимов? :) Исправлю
