### ISSUE TITLE
Возможность полностью скрыть хентай из сайта

### ISSUE THREAD

**Issue by bicolino34** [shikimori/shikimori#2168]

**Comment by Moltenship** [comment]
Не надо 😢

**Comment by RuSaG0** [comment]
Это будет лишним

**Comment by bicolino34** [comment]
> Это будет лишним

Да я и не говорю о полном удалении. Я хочу добавления опции настройки, чтобы можно было полностью скрыть хентай.

**Comment by BoberMod** [comment]
> > Это будет лишним
> 
> Да я и не говорю о полном удалении. Я хочу добавления опции настройки, чтобы можно было полностью скрыть хентай.

А откуда именно скрыть? При переходе на 18+ требуется подтверждение возраста, а сами тайтлы нигде не выводятся без фильтра.

**Comment by bicolino34** [comment]
> > > Это будет лишним
> > 
> > 
> > Да я и не говорю о полном удалении. Я хочу добавления опции настройки, чтобы можно было полностью скрыть хентай.
> 
> А откуда именно скрыть? При переходе на 18+ требуется подтверждение возраста, а сами тайтлы нигде не выводятся без фильтра.

Хмм... У меня в профиле указан возраст меньше 18 лет и в поиске, даже без фильтра, выскакивает хентай. Возможно баг.
