### ISSUE TITLE
[OAuth2] add support scope for receiving email

### ISSUE THREAD

**Issue by negezor** [shikimori/shikimori#2224]
It would be nice to add an email to receive in OAuth2. I ran into the problem of duplicate accounts, and the easiest option would be to merge them by email.

**Comment by morr** [comment]
@negezor why can't you use user id?
![image](https://user-images.githubusercontent.com/134610/117854349-1576ab00-b292-11eb-91f1-a84f2038b93c.png)

**Comment by negezor** [comment]
This is the only way to get a profile after OAuth authorization? If so, then it is worth returning an email with `scope:email`

**Comment by negezor** [comment]
@morr, https://shikimori.one/oauth/applications/443

**Comment by morr** [comment]
Done
