### ISSUE TITLE
[api] refresh token error invalid_grant

### ISSUE THREAD

**Issue by DENNKA** [shikimori/shikimori#2326]
Error when refreshing token

`
{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
`

Occurred when i used [python shikimori_api (requests_oauthlib)](https://github.com/nomnoms12/shikimori_api)
Example from https://shikimori.one/oauth not works too
```
curl -X POST "https://shikimori.one/oauth/token" \
-H "User-Agent: trp" \
-F grant_type="refresh_token" \
-F client_id="XXX" \
-F client_secret="XXX" \
-F refresh_token="XXX"
```
I'm try to add ```-F redirect_uri="urn:ietf:wg:oauth:2.0:oob"```, but this also not work

token:
`
{"access_token": "XXX", "token_type": "Bearer", "expires_in": 86400, "refresh_token": "XXX", "scope": ["user_rates"], "created_at": 1638129418, "expires_at": 1638215818.5084262}
`

**Comment by morr** [comment]
@DENNKA ничем не могу помочь с использованием сторонней библиотеки, обращайтесь к её автору или разбирайтесь самостоятельно.

На этой странице https://shikimori.one/oauth вручную по шагам пройти все шаги oauth2 авторизации, в том числе обновить токен. Смотрите, какой получается запрос на тестовой странице, и в чём отличие в вашем коде.
