### ISSUE TITLE
review fixes and improvements

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#2334]
- [ ] есть предложение отображать отзывы на главной, так же как рецензии (например сразу под рецензиями).
- [x] изменение комментария на отзыв не фиксируется в журнале модерации, запись исчезает и найти этот отзыв потом невозможно.
- [x] у отзывов очень сильно не хватает истории жалоб. Нельзя посмотреть, были ли запросы на снятие отзыва/жалобы ранее.
- [x] Ответы на отзыв не добавляются в ббкод [repiles] у отзыва
- [x] При просмотре в профиле пользователя непонятно к чему отзыв и нет возможности сразу перейти к тайтлу.
- [x] Скрыть ссылки на ответы у самого отзыв (за ненадобностью).
- [x] Эти ответы (коменты) "отвечают" не на новый отзыв, а на старый удаленный отзыв-комент (/animes/z5114-fullmetal-alchemist-brotherhood/reviews/66404).
- [x] Шрифт слишком большой (сравни с теме же "кадрами" и "видео").
- [ ] Очень большие кнопки ("коментировать", "ко всем отзывам", "написать отзыв") - выходит грамостко и выбивается из общего тона.
- [x] Когда нет отзывов, ломается отображение на телефоне (/comments/7882818).
- [x] Изменение комментария на отзыв не фиксируется в журнале модерации, запись исчезает и найти этот отзыв потом невозможно.
- [x] Broken review->comment conversion when review has ban record
- [x] удалить кнопку Комментировать у отзывов
- [x] не приходят уведомления при ответах на отзыв
- [x] Отображать кол-во отзывов со ссылкой в блоке "У аниме"
- [x] Добавить кнопки действий для отзывов на index страницу
- [x] Validate review.db_entry url https://shikimori.one/animes/45576-mushoku-tensei-isekai-ittara-honki-dasu-part-2/reviews/7

**Comment by adem4ik** [comment]
Предлагаю убрать возможность выставить полезность у собственного отзыва в своём профиле `https://shikimori.one/<my_user>/reviews` и в самом тайтле:
![image](https://user-images.githubusercontent.com/4707112/146610290-d67d209b-78cb-4bad-9168-2d9ed6a0b816.png)

**Comment by adem4ik** [comment]
Ещё пожелание - отображать кол-во отзывов рядом с кол-вом комментариев в блоке тайтла.
Например: `У аниме: 38 отзывов, 1296 комментариев`
При чём `38 отзывов` должно быть ссылкой на `https://shikimori.one/animes/<title>/reviews` , т.е. аналогично комментариям

![image](https://user-images.githubusercontent.com/4707112/146612932-c1bfac1b-3d7b-4e74-83e2-0aadc9b52212.png)

**Comment by morr** [comment]
@adem4ik забыл про это, спасибо! Сделаю
