### ISSUE TITLE
У Кинопоиска поменялся логотип

### ISSUE THREAD

**Issue by adem4ik** [shikimori/shikimori#2341]
Источник: https://www.kinopoisk.ru/media/news/4005309/

- На данный момент Шики использует старый 
![image](https://user-images.githubusercontent.com/4707112/146606867-49748d33-1cbe-422a-8e09-d126e765b3a4.png)

- Новая фавиконка тут https://www.kinopoisk.ru/favicon.ico , на основе неё смастерил 2 версии:
![kinopoisk32](https://user-images.githubusercontent.com/4707112/146607216-abad4c30-687b-460a-bc15-1f650e7143ae.png)
![kinopoisk64](https://user-images.githubusercontent.com/4707112/146606936-99141d15-29c3-4fb7-a70e-c79c8a1e56e9.png)

**Comment by morr** [comment]
@adem4ik, спасибо! обновил.
