### ISSUE TITLE
Нет возможности войти в аккаунт

### ISSUE THREAD

**Issue by drov-drov** [shikimori/shikimori#2369]
Не уверен, что об этом стоит писать здесь, но, на всякий случай, опишу проблему. После смены никнейма (drov-drov > MRZG65RNMRZG65QK) пропала возможность войти на сайт. Пароль не менял, почта временная (доступа нет). Как можно решить проблему? Кроме создания нового аккаунта, конечно.

**Comment by morr** [comment]
@drov-drov напишите сюда, какую почту привязать к аккаунту (после прочтения удалю емайл из публичной переписки). или на почту admin@shikimori.org
не пускает 99% потому, что вводите неправильный пароль.
Хм хотя я не понимаю, почему вас выкинуло с аккаунта. При смене логина этого не происходит (на тестовых акканутах не могу воспроизвести)

**Comment by drov-drov** [comment]
@morr, `drov-drov@tuta.io`
На почту тоже отправил

**Comment by morr** [comment]
@drov-drov сделал! Восстановить пароль теперь можно по ссылке https://shikimori.one/users/password/new

**Comment by drov-drov** [comment]
Если не принципиально, то пожалуйста, удалите ишшу.

**Comment by morr** [comment]
@drov-drov issue удалить невозможно на гитхабе. удалил содержимое вашего первого сообщения
