### ISSUE TITLE
Is is_nickname parameter in api/users/:id redundant?

### ISSUE THREAD

**Issue by SecondThundeR** [shikimori/shikimori#2418]
I'm not sure, but according to [method to get user in users_controller.rb](https://github.com/shikimori/shikimori/blob/master/app/controllers/api/v1/users_controller.rb#L220-L228), if we try to get user by nickname without using is_nickname parameter, we will still get user info after failing parameter check, but passing [second check](https://github.com/shikimori/shikimori/blob/master/app/controllers/api/v1/users_controller.rb#L225-L226).

Therefore, why do we need this parameter if the else block contains almost the same code?

**Comment by Yokitori** [comment]
> Therefore, why do we need this parameter if the else block contains almost the same code?

It's not redundant because we have bunch of nicknames containing only numbers (but having different ids), and may be kept for api backward compatibility anyway.

**Comment by SecondThundeR** [comment]
> we have bunch of nicknames containing only numbers (but having different ids)

Oh, didn't even think that someone really could have such usernames, so it makes sense. Thanks for the answer!
