### ISSUE TITLE
Problem with PATCH request body for /api/clubs/:id

### ISSUE THREAD

**Issue by SecondThundeR** [shikimori/shikimori#2424]
In the [parameters](https://shikimori.one/api/doc/1.0/clubs/update) for the request body, there are a couple of policy fields which apparently do not accept JSON strings.

Example of request and response:
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/36604233/168158847-0ec6e36b-fffc-4d60-8c94-bf8b5c174d25.png">

Other fields like `name`, `description` are fine, because they are standard types. However, there are problems with `display_images` field too, where it appears to work incorrectly when sending request body with value `false`, when with value `true` everything is fine

Example of request and response with value `true`:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/36604233/168157192-bedfde94-02f8-47b0-8524-85c94d2edfc4.png">

Example of request and response with value `false`:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/36604233/168157216-e76035c6-3c2c-458d-819a-573e3f8e8103.png">

**Comment by morr** [comment]
@SecondThundeR fixed
