### ISSUE TITLE
filter by genres is not working in api/animes

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#2463]
Здраствуйте! В API (v1) по пути /animes со списком аниме, не работает параметр genre. Выдает тот же список что и без него, пожалуйста поправте ^_^

**Comment by Yokitori** [comment]
> Здраствуйте! В API (v1) по пути /animes со списком аниме, не работает параметр genre. Выдает тот же список что и без него, пожалуйста поправте ^_^

Can't reproduce, need more info with examples.

Queries like `https://shikimori.one/api/animes?page=2&limit=50&genre=40`, `https://shikimori.one/api/animes?page=1&limit=50&genre=40,41&mylist=completed` (with or without `mylist` or login) seems working as expected.
