### ISSUE TITLE
Баги/доработки модерации

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#2475]
Хотелось бы дополнительно узнать 3 момента насчёт новостей:

- [x] 2.Не знаешь из-за каких обстоятельств новости с сайта отсутствуют в новостных агрегаторах (яндекс новости / google news)? Из-за отсутствия премодерации или ещё из-за каких-то причин?
- [x] 3.Плашка "оффтоп" на новостях банально убирает новость с главной страницы и больше ничего не делает, даже визуально на новостях её нет. Есть ли планы по поводу изменения системы оффтопа у новостей? (на гитхабе не замечал по этому поводу ничего)

Также насчёт статей кое-что хотелось бы уточнить:

- [x] 1.Модератор статей не может удалять статьи в разделе модерации статей, удалять статьи могут только модераторы форума. Так и было задумано?
- [x] 2.Премодерация статей будет работать точно также, как в разделе модерации новостей?

- [x] В разделе новостей вскрылся ещё один баг: только на страницах аниме сбоку появляется блок "новости", со всеми новостями, где указан этот тайтл в "связанном". У людей, персонажей, манги и ранобэ этот блок не появляется, при соблюдённом условии, что страница с человеком / тайтлом указана в "связанном".

**Comment by Yokitori** [comment]
> 1.Новости, отредактированные модератором / юзером после принятия изменений высвечиваются первой новостью на форуме. Это баг или фича?

Из-за сортировки по update_at так происходит вообще со всеми топиками.

**Comment by Yokitori** [comment]
Moved
>Также с новыми отзывами заметил один баг / фичу. Раньше любой пользователь мог сделать репорт на комментарий, чтобы его преобразовали в отзыв, фича хоть была непопулярной, но полезность у некая имелась. Теперь пользователь не может подать репорт на чужой комментарий, чтобы его преобразовали в отзыв, только может сделать наоборот (отправить репорт на отзыв, чтобы его преобразовали в комментарий).

to #2516
