### ISSUE TITLE
Возможность добавить несколько redirect url для oauth2 приложений

### ISSUE THREAD

**Issue by MWGuy** [shikimori/shikimori#2500]

**Comment by MWGuy** [comment]
Сейчас приходится костылить, если приложение имеет несколько доменов (к примеру: manga.ovh и ranobe.ovh), а так же если у приложения есть нескольно oauth2 эндпоинтов (к примеру: авторизиция, привязка сервиса к уже сущесвующему аккаунту)

**Comment by morr** [comment]
@MWGuy поменял на textarea. дополнительные домены добавляются с новой строки

**Comment by websorokinweb** [comment]
04.11.23 снова input, а не textarea. Появилась ли новая возможность прописывать несколько redirect uri?

[https://some-https-app,http://localhost:3000]
