### ISSUE TITLE
private clubs and shadowbans

### ISSUE THREAD

**Issue by Yokitori** [shikimori/shikimori#2546]
- [ ] скрывать клуб в clubs#index, если ты не моератор и не мембер клуба
- [ ] не отправлять в faye канал данные о комментариях такого клуба (но нужно еще покопаться, как сделать так, чтобы в самом клубе faye работал, а на форуме - нет)
- [ ] скрывать в user#comments комментарии из такого клуба, если ты не моератор и не мембер клуба
- [ ] выдавать 404 в comments#show у комментариев такого клуба, если ты не моератор и не мембер клуба

**Comment by morr** [comment]
сделал в другом тикете
