### ISSUE TITLE
api/v2/user_rates parameter user_id always is required

### ISSUE THREAD

**Issue by pont1s** [shikimori/shikimori#2576]
При использовании метода api/v2/user_rates без параметров, для получение списка оценок пользователя, авторизованного через OAuth, возвращается ошибка `Missing parameter user_id`

Воспроизведение:
авторизовавшись, перейти по [https://shikimori.one/api/v2/user_rates](https://shikimori.one/api/v2/user_rates)

#2538 данный Issue вроде бы поднимал эту проблему.

**Comment by morr** [comment]
@pont1s так и задумано. все подряд user rates сайт не позволяет запрашивать (нет в этом никакого смысла), только по конкретному пользователю
