### ISSUE TITLE
Poster previews are not showing on iPhone 6S

### ISSUE THREAD

**Issue by BoberMod** [shikimori/shikimori#2616]
Only previews are not displaying, but full versions are ok. So, basically, you need to open anime or character page to view posters, but they are not showing on search or home page. 
Also, it's not related to assets caching or connection problems because previews load correctly when you follow a direct link (both .webp and .jpg)

Device: iPhone 6S, iOS 15.7.2
**Report on behalf of another person, I can't verify by myself**

<details>
  <summary>Screenshots</summary>
  
  ![image](https://user-images.githubusercontent.com/8740496/212535871-a19aaa44-349a-4ace-9752-39e74a51c744.png)
  ![image](https://user-images.githubusercontent.com/8740496/212535877-5074a398-f2e8-4eb4-ae66-82730019fe94.png)
  
</details>

**Comment by morr** [comment]
@BoberMod thanks! Fixed.
