### ISSUE TITLE
Потеря достижения

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [shikimori/shikimori#2629]
Здравствуйте,

В последнее время заметил странностью. Некоторое время назад отметил одно аниме как просмотренное после чего высветилось оповещение о том что потеряно достижение (название к сожалению не помню). А сейчас отметил аниме "Персиковый мальчик, пришедший с другого побережья" и потерял достижение "Первая встреча с духами". 

Подскажите почему так?

**Comment by morr** [comment]
@Eldrinn-Elantey такое иногда происходит
1) с франшизными ачивками.
Например, ачивка может выдаваться за какую-то франшизу, если просмотрено 80% аниме этой франшизы. А потом у какого-то аниме из этой франшизы выходит второй сезон или полнометражка. Те просмотренные аниме, которых хватало засчитать за 80%, начинают давать лишь 70 или 75 процентов из-за увеличившего хронометража франшизы из-за выхода новых аниме. Поэтому иногда франшизные ачивки слетают.
2) с жанровыми ачивками
Тут ситуация в чем-то похожа. Иногда модераторы меняют жанры у аниме, ДДобавляют новые или убирают старые.
И если раньше какое-то аниме засчитывалось в жанр сверхъестественное, то после удаления этого жанра у аниме, оно перестает засчитываться в ачивку.

Это про то, почему ачивки могут слетать.

Теперь про то, почему ачивки выдаются/убираются при добавлении в список не связанных с ачивкой аниме.
Так работает система ачивок на сайте :)
Сайт не отслеживает ачивки, связанные с конкретным аниме. При любом изменении списка сайт рассчитывает для пользователя **все** его ачивки заново.

**Comment by Eldrinn-Elantey** [comment]
@morr Спасибо за быстрый ответ.

Предполагал нечто подобное но всё же решил спросить об этом. Спасибо за подробный ответ
