### ISSUE TITLE
Добавить свои списки (пользователь сам указывает название списка)

### ISSUE THREAD

**Issue by OmlineEditor** [shikimori/shikimori#2638]
Прошу сделать возможность создавать **_свои_** списки аниме в дополнение к основным что есть на сайте (ЗАПЛАНИРОВАНО, СМОТРЮ, ПРОСМОТРЕНО и т.д.)

Лично мне не хватате еще списков:
- Жду перевод (нет перевода на русский)
- Мусор (смотреть точно не буду)
- Следующее на очереди

Пусть эти списки будут только видны самому пользователю и никак не влияют на рейтинг или статистику что вы ведете по основным спискам.
Такие списки есть на сайте www.world-art.ru и это очень удобно.
Другим пользователям эти списки тоже помогут лучше сортировать аниме и мангу.

**Comment by Edzura** [comment]
Duplicate of #1719
