### ISSUE TITLE
Facebook auth error

### ISSUE THREAD

**Issue by simbiant** [shikimori/shikimori#2666]
При попытке авторизироваться через facebook пишет
Ошибка доступа к приложению. К сожалению, приложение, которое вы пытаетесь использовать больше не существует или отключено
![image](https://user-images.githubusercontent.com/24406976/229368491-881001ec-18e0-4cbf-80c7-5ceedbc8e20b.png)

**Comment by morr** [comment]
@simbiant https://shikimori.one/facebook
