### ISSUE TITLE
У вас тут ссылка старая

### ISSUE THREAD

**Issue by Sanceilaks** [shikimori/shikimori#2673]
![browser_sDJolIfi1v](https://user-images.githubusercontent.com/39582793/232143331-0896c3e6-ef14-4096-be02-4215dd37aeea.png)

**Comment by websorokinweb** [comment]
а как новую найти?

**Comment by plush-mesh** [comment]
https://shikimori.me

https://github.com/shikimori/shikimori/commit/139a590992b1239c030f2de2515d79f1456b5c74
> `- https://shikimori.one`
> `+ https://shikimori.me`

**Comment by plush-mesh** [comment]
https://shikimori.me/forum/news/505429-novyy-domen-sayta-shikimori-me

**Comment by Sanceilaks** [comment]
> https://shikimori.me
> 
> [2df4638](https://github.com/shikimori/shikimori/commit/2df463833e9b475230a640aef6adf7b0ed88aa93) [97365cb](https://github.com/shikimori/shikimori/commit/97365cb6a6da1680e2380128439b1dd2131340e9) [139a590](https://github.com/shikimori/shikimori/commit/139a590992b1239c030f2de2515d79f1456b5c74)
> 
> > `- https://shikimori.one`
> > `+ https://shikimori.me`
> 
> **Update** (15.04.2023): https://shikimori.me/forum/news/505429-novyy-domen-sayta-shikimori-me

да я об этом и говорю. везде изменили, а в описании нет
