### ISSUE TITLE
Пагинация Animes API возвращает не N+1 при наличии следующей страницы

### ISSUE THREAD

**Issue by Smarthard** [shikimori/shikimori#2684]
Пример: https://shikimori.me/api/animes?limit=1 - вернется ровно один

```json
[
  {
    "id": 2092,
    "name": "Kiss wa Hitomi ni Shite",
    "russian": "Поцелуй в глазик",
    "image": {
      "original": "/system/animes/original/2092.jpg?1674342361",
      "preview": "/system/animes/preview/2092.jpg?1674342361",
      "x96": "/system/animes/x96/2092.jpg?1674342361",
      "x48": "/system/animes/x48/2092.jpg?1674342361"
    },
    "url": "/animes/2092-kiss-wa-hitomi-ni-shite",
    "kind": "ova",
    "score": "5.68",
    "status": "released",
    "episodes": 1,
    "episodes_aired": 0,
    "aired_on": "1993-08-27",
    "released_on": null
  }
]
```

И так с любым количеством limit в рамках валидных значений.

Ожидаемое поведение:

При запросах с limit=N в ответе должно приходить N+1, если есть следующая страница. Как, например, сейчас это делает Users API: https://shikimori.me/api/users?limit=1

Скорее всего баг, во всяком случае, в документации не нашел упоминаний того, что пагинация должна вести себя по-другому для аниме.

**Comment by morr** [comment]
@Smarthard не баг. исправлено не будет. так исторически сложилось. каталог аниме использует тот же самый код, что используется для отображения каталога аниме на основном сайте, и там N+1 отсутствует. переделывать не буду

Вообще N+1 пришло из моего прошлого опыта энтерпрайз разработки. Весьма неудобным оно на практике вышло, проще проверять наличие следующей страницы проверкой `collection.size == per_page_limit`
