### ISSUE TITLE
User-Agent Naming for Applications

### ISSUE THREAD

**Issue by nattadasu** [shikimori/shikimori#2692]
Hello!

I noticed that in [Shikimori API 1.0 documentation](https://shikimori.me/api/doc/1.0) stated that:

* `User-Agent` must be named after application name
* `User-Agent` must not mimic browser's UA

My question: Can developer uses User-Agent that includes their version of the bot and additional information, or does this count as mimicking browser's UA?

What I mean is similar what I did to my project:

```http
User-Agent: UserAgentTest/1.0 (github:repo/aabbccd; branch:main; author:user:112233445566; https://example.com)
```

Should dev name their User-Agent as what the example provided, or is it strictly use `UserAgentTest` instead as the example mimics browser?

**Comment by morr** [comment]
> Should dev name their User-Agent as what the example provided, or is it strictly use UserAgentTest instead as the example mimics browser?
It does not really matter what you choose. Both variants are acceptable.
