### ISSUE TITLE
При попытке сменить ник с окончанием .json вылезает ошибка об отсутствии темплейта

### ISSUE THREAD

**Issue by NekonexDev** [shikimori/shikimori#2694]
Кепка

**Comment by morr** [comment]
@NekonexDev, больше не должно падать

**Comment by morr** [comment]
@NekonexDev ааа. я немного не то пофиксил. теперь нельзя выставить никнеймы, оканчивающиеся на .json
 уже имеющиеся я не фиксил. сейчас попровил их. переименованы `all.json` -> `all_json`, `page-1.json` -> `page-1_json`

**Comment by morr** [comment]
@NekonexDev нет. никнеймы, ломающие сайт в разных местах, не нужны
