### ISSUE TITLE
Посещаемость сайта

### ISSUE THREAD

**Issue by nvd05** [shikimori/shikimori#2699]
При просмотре `https://shikimori.me/about` я заметил резкое падение статистики после 14 апреля.
Почему такое произошло? (ведь сейчас `.one` работает в штатном режиме, однако активность не повысилась).

Из рекомендаций - совет - сделай статистику по доменам.
То есть, чтобы в графиках с просмотрами, итд - отображалось с какого домена (`.me` or `.one`).

Тогда будет что-то подобное:
```txt
Уникальных пользователей .one => N_COUNT,
Уникальных пользователей .me => N_COUNT,
Уникальных пользователей всего => N_COUNT
```

**Comment by morr** [comment]
@nvd05 .one делает редирект на .me, поэтому новой статистики там нет
на .me новый счетчик, если /about поставить загрузку с нового счетчика, то данные от старого не будут отображать, а мержить данные с двух счетчиков мне лень.
потом как-нибудь поменяю

если интересны цифры, то сейчас 105-110к человек в день
![image](https://github.com/shikimori/shikimori/assets/134610/e58729f6-e76f-4a47-aa57-6a147188b5bc)

а если считать людей без адблока, то 240к в день
<img width="701" alt="image" src="https://github.com/shikimori/shikimori/assets/134610/876c51cb-03ec-447d-93e1-d743308d79ef">

**Comment by morr** [comment]
@nvd05 можно написать стили, а можно ничего не писать и просто использовать адблок
