### ISSUE TITLE
Обновить документацию

### ISSUE THREAD

**Issue by imPDA** [shikimori/shikimori#2702]
В APIv1 в эндпоинте /users не хватает документации, например, там работает поиск, который не отражён.

Текущее поведение:
принимается параметр search:
![image](https://github.com/shikimori/shikimori/assets/43822452/304bde76-f323-4e52-8fac-ae1afde6b42e)

Поведение по документации:
search приниматься не должен, список доступных параметров:
![image](https://github.com/shikimori/shikimori/assets/43822452/fb1a4dbf-1c2c-44c2-bbe8-95fee7848167)

Возможные исправления:
дополнить описание эндпоинта:
- параметр search(необязательный): максимальная длина ..., допустимые символы ... 
- ... другие параметры, если они отсутствуют в описании ...

**Comment by morr** [comment]
@imPDA сделал
