### ISSUE TITLE
custom_css @import обрезает ссылку

### ISSUE THREAD

**Issue by nvd05** [shikimori/shikimori#2705]
По какой-то причине `@import` обрезает ссылку.

```css
@import url(https://shiki-theme.web.app/import/theme-default.css);
/* https://shiki-theme.web.app//theme-default.css */
```

![Снимок экрана (2920)](https://github.com/shikimori/shikimori/assets/69719657/2b2e9d38-f773-4544-8f00-a65dfd7f006b)

**Comment by grin3671** [comment]
Можно временно использовать папку "stable":
```css
@import url("https://shiki-theme.web.app/stable/theme-default.css");
```
К сожалению, исправить путь для всех пользователей я не могу, а поддерживать сразу оба не получится.

**Comment by morr** [comment]
@nvd05, @grin3671 не вижу проблемы. сам импорт ведь происходит? происходит. а то, что ссылка в содержимом комментария портится - это можно не фиксить, оно ни на что не влияет. или я что-то не так понял?
