### ISSUE TITLE
Добавить при экспорте в файл название на русском языке

### ISSUE THREAD

**Issue by OmlineEditor** [shikimori/shikimori#2737]
Сейчас при экспорте есть название на английском, вот так:

```
"target_title": "Witch Craft Works",
"target_id": 21085,
...
```

Прошу сделать так чтобы было еще и название на русском **_target_title_ru_,** вот так:
```
"target_title": "Witch Craft Works",
"target_title_ru": "Ведьма за работой",
"target_id": 21085,
...
```

Так намного проще и удобнее будет работать

**Comment by morr** [comment]
@OmlineEditor добавил
