### ISSUE TITLE
Tooltip styling

### ISSUE THREAD

**Issue by McFck** [shikimori/shikimori#2738]
Suggest adding small padding to text block in tooltip. Currently there is an issue related to text overlapping.

![image](https://github.com/shikimori/shikimori/assets/29148980/73a82412-63b0-47cb-9199-e787da16cf0c)

https://github.com/shikimori/shikimori/blob/ee1c3d4e37047cad829e3ee50a5779b0b15e4362/app/assets/stylesheets/application.sass#L70C1-L70C1
Maybe here, some padding ~3px will do the trick

![image](https://github.com/shikimori/shikimori/assets/29148980/bdfb9279-7be4-4d5f-9f6f-92950af5234d)

**Comment by morr** [comment]
@McFck так сделано специально. Нужно либо ухудшать тултип, добавляя бОльший верхний и правый паддинг, либо оставить как есть. То, что крестик иногда частично перекрывает одну букву, мне кажется меньшим злом.
