### ISSUE TITLE
Broken GraphQL manga request

### ISSUE THREAD

**Issue by McFck** [shikimori/shikimori#2740]
Вот эта строчка вызывает отвал графкла при запросе манги со статусом, которого нету у аниме, типа 'приостановлено'. https://github.com/shikimori/shikimori/blob/ee1c3d4e37047cad829e3ee50a5779b0b15e4362/app/graphql/types/enums/status_enum.rb#L4C3-L4C3

Вот кверя для теста, ранобе в статусе приостановлено, вернет ошибку.
```
{
  mangas(page: 1, ids: "55869") {
    id
    status
  }
}
```

**Comment by McFck** [comment]
Также и обычный v1 api отваливается, но уже похоже по другой причине, нету возможности продебажить к сожалению.
https://shikimori.me/api/users/1121790/manga_rates

**Comment by morr** [comment]
@McFck пофиксил. у манги есть еще несколько статусов, которые в graphql типе не были описаны
