### ISSUE TITLE
Broken API for /users/:id/anime_rates endpoint

### ISSUE THREAD

**Issue by IM1corp** [shikimori/shikimori#2741]
My shikimori profile: [yummyanime](https://shikimori.me/yummyanime) (id = `1375779`)
When I'm trying to get anime_rates from API (GET `https://shikimori.me/api/users/1375779/anime_rates`), I'm getting next error:

`"undefined method fetch_value for nil:NilClass"`

If I use nickname instead of id: (GET `https://shikimori.one/api/users/yummyanime/anime_rates`) api works, **BUT** it returns only first 2 animes. 
When i add any GET parameter (limit/offset/page, ect.):  (GET `https://shikimori.me/api/users/1375779/anime_rates?limit=10`) it returns `"undefined method fetch_value for nil:NilClass"` again.

**Comment by McFck** [comment]
mentioned it already here https://github.com/shikimori/shikimori/issues/2740

**Comment by morr** [comment]
@IM1corp, @McFck это артефакт апгрейда руби до 3.2. скорее всего оно пофикселось несколько недель назад, когда я обновил некоторые зависимости
