### ISSUE TITLE
Настакивание padding'ов в .b-catalog_entry

### ISSUE THREAD

**Issue by grin3671** [shikimori/shikimori#2742]
Из-за свойства `padding-right: 5px` в [селекторе](https://github.com/shikimori/shikimori/blob/2d59e21d4acc87a952427a6366aabc1c10b09e7f/app/assets/stylesheets/blocks/b-catalog_entry.sass#L124) `.b-catalog_entry .cover .misc span` и вложенных `span` в некоторых элементах вроде [лучших работ людей](https://shikimori.me/people/1-tomokazu-seki) места для текста внутри этих `span` остаётся крайне мало (особенно заметно на при ширине сайте в 1000px).
Предлагаю убрать этот `padding-right: 5px`, а также `padding-right: 0px` у [селектора](https://github.com/shikimori/shikimori/blob/2d59e21d4acc87a952427a6366aabc1c10b09e7f/app/assets/stylesheets/blocks/b-catalog_entry.sass#L141) `.b-catalog_entry .cover .misc span.right` и добавить к нему же `margin-left: 5px` для сохранения отступа.

![](https://i.imgur.com/8WfoyFh.jpg)

Также было бы неплохо добавить в репозиторий label `СSS` для подобных проблем.

**Comment by morr** [comment]
@grin3671 древняя верстка, сделанная во времена, когда flex не все браузеры поддерживали. сделаю у контейнера `display: flex` + `gap: 5px`
