### ISSUE TITLE
Оценка на превью внешней ссылки указывается как 0.0.

### ISSUE THREAD

**Issue by opa-oz** [shikimori/shikimori#2755]
https://shikimori.me/animes/50594-suzume-no-tojimari

Превью:
![50594](https://github.com/shikimori/shikimori/assets/34550675/97baf774-c5b9-4448-8c21-8bc11585ce03)

Сейчас 8.35, немножко запаздывает.

А, и английский текст

**Comment by opa-oz** [comment]
![50594](https://github.com/shikimori/shikimori/assets/34550675/ab5ecda6-96ce-4cf2-be1b-c23707692d23)

Тадааааа

**Comment by morr** [comment]
@opa-oz спасибо!

**Comment by opa-oz** [comment]
@morr Кхм-кхм https://github.com/shikimori/shikimori/pull/2756 ❤️

**Comment by morr** [comment]
@opa-oz упс... прошу прощения, я не увидел новые PRы в проекте. Мне столько уведомлений по работе от гитхаба проходит, что я практически перестал читать этот поток спама в почте :/
