### ISSUE TITLE
Кривой поиск по двойному названию Ru / Eng

### ISSUE THREAD

**Issue by OmlineEditor** [shikimori/shikimori#2758]
Ввожу в поиск слова: "**_Стесняшка / Shy_**" Два слова через слеш (так многие пишут по двойному названию через слеш)
В результатах поиска что угодно кроме нужного аниме.
Удаляю слеш оставляю только два слова, все тоже самое ничего нет.
Удаляю одно из слов, неважно какое, и в первой же строке нужно мне аниме.

Испраьте поиск аниме при указании двойного названия: **_Ru / Eng_**

**Comment by morr** [comment]
@OmlineEditor это не будет исправлено

**Comment by OmlineEditor** [comment]
Почему? В чем проблема сделать поиск по корреляции? Вы ищите и по русскому и по английскому названию порознь, думаю можно сделать поиск при совпадении части названия более релевантным.

**Comment by morr** [comment]
@OmlineEditor сайт уже и так возвращает результаты, отсортированные по релевантности. из-за наличия в искомой строке второго названия (русского или английского) релевантность подсчитывается неправильно. относительно простого и быстрого решения для этой проблемы у меня нет, а делать сложный фикс, перестраивать логику работы поиска я не буду. раньше я уже пробовал делать индекс для поиска, содержащий одновременно все возможные названия аниме в одном поле, и искать сразу среди всех названий. подобный подход давал худшие результаты поиска, чем текущая реализация.

**Comment by OmlineEditor** [comment]
Спасибо за пояснение :-)
