### ISSUE TITLE
Feature Request: decrease (rollback) button in user_rate

### ISSUE THREAD

**Issue by yunfachi** [shikimori/shikimori#2761]
![prototype](https://github.com/shikimori/shikimori/assets/73419713/327726d4-6c45-4e99-9933-3b73a730dc3c)
Add a `decrease` button (`rollback` in the code), opposite the existing 'increase' button. This addition would be highly beneficial, especially in cases where the `increase` button is accidentally clicked, as it would eliminate the need to navigate through lists and edit the page manually.

Добавить кнопку `decrease` (`rollback` в коде) противоположную по значению существующей кнопке `increase`. Это будет очень полезным в случаях, когда кнопка `increase` была нажата случайно, так как оно позволит избежать необходимости вручную переходить к спискам и редактировать страницу.

**Comment by grin3671** [comment]
> необходимости вручную переходить к спискам и редактировать страницу

Можно нажать на «Смотрю» на синей кнопке сверху и исправить данные. К сожалению, дизайн кнопки не позволяет понять, что это не только выпадающий список для изменения категории.
