### ISSUE TITLE
Более широкий выпадающий список для добавления аниме в коллекцию

### ISSUE THREAD

**Issue by OmlineEditor** [shikimori/shikimori#2774]
При добавлении аниме в список коллекции, когда вводишь часть названия аниме помещается не всё. Названия в конце обрезается и получается при длинном названии аниме ничего не понятно, одни и теже названия, только года меняются.
Понять при таком списке что либо сложно. Поэтому прошу увеличить ширину этого списка до максимально возможного, а всё что не влезло пусть будет возможность показать во всплывающем меню с переносом строк при наведении курсора.

![list](https://github.com/shikimori/shikimori/assets/13348933/06d3f374-117e-4982-8e26-bb4a111c2014)

**Comment by morr** [comment]
@OmlineEditor теперь будет растягиваться на всю ширину поля ввода
