### ISSUE TITLE
Добавить поддержку YouTube Shorts ссылок.

### ISSUE THREAD

**Issue by nvd05** [shikimori/shikimori#2782]
Пример ссылки:

```text
https://youtube.com/shorts/yFg1-tIfvjc?si=6VLqJBX6zoeXrja2
```

**Comment by nvd05** [comment]
@morr, добавьте пожалуйста в теги: `shiki_editor_v2`

**Comment by POMATu** [comment]
у меня есть более актуальное предложение: сделать так что бы плеер rutube начал встраиваться
![image](https://github.com/user-attachments/assets/70e68441-ee28-47d1-9c12-52e99708d095)
