### ISSUE TITLE
BUG. API Graphql

### ISSUE THREAD

**Issue by gyxoBka** [shikimori/shikimori#2792]
### При запросе тайтла по id: 41219 возникает след ошибка:

> {
>     "errors": [
>         {
>             "exception": "Types::Enums::ExternalLink::KindEnum::UnresolvedValueError",
>             "message": "`ExternalLink.kind` returned `\"ivi\"` at `animes.0.externalLinks.5.kind`, but this isn't a valid value for `ExternalLinkKindEnum`. Update the field or resolver to return one of `ExternalLinkKindEnum`'s values instead."
>         }
>     ]
> }

`
query($ids: String) {
    animes(ids: $ids) {
        externalLinks {
          kind
          url
        }
    }
}
`

`
{"ids": "41219"}
`

**Comment by morr** [comment]
исправлено... не помню когда, довольно давно уже
