### ISSUE TITLE
[Предложение] Добавить в API возможность отдельно запросить Open Graph поля

### ISSUE THREAD

**Issue by LennyLizowzskiy** [shikimori/shikimori#2836]
(эти - https://ogp.me/)

Они есть на каждой страничке, но их можно получить только если запросить полноценную страничку и отпарсить её, что рекомендуется не делать в документации API

**Comment by morr** [comment]
@LennyLizowzskiy в этих поля лежит ссылка, картинка, описание. все эти поля доступны в graphql апи

**Comment by LennyLizowzskiy** [comment]
> @LennyLizowzskiy в этих поля лежит ссылка, картинка, описание. все эти поля доступны в graphql апи

превью, которое на anime-recommend.ru лежит, разве доступно?

**Comment by morr** [comment]
@LennyLizowzskiy аа понял, о чем речь. вот это http://cdn.anime-recommend.ru/previews/52991.jpg. добавлю в апи.

**Comment by morr** [comment]
@LennyLizowzskiy  добавил https://github.com/shikimori/shikimori/commit/de115e1a6f4377fc2a14303275229ad14959edb4
