### ISSUE TITLE
neko achievements

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#324]
1) http://github.com/rr-/malgraph4/tree/master/data/achievements
2) http://wiki.anidb.net/w/Achievements
3) на anime-planet.com
4) https://forums.hummingbird.me/badges

**Comment by morr** [comment]
@tap346, bug:
1. создаю пользователя
2. добавляю 4 аниме в список https://shikimori.org/achievements/franchise/hikaru_no_go
3. получаю ачивку
4. удаляю одно из аниме из списка
5. ачивка не пропадает

**Comment by tap349** [comment]
1. удаляем ачивки

```ruby
user = User.find(1); user.achievements.destroy_all; Achievements::Track.new.perform user.id, nil, 'reset'
```

2. делаем `reset` - получаем все новые ачивки
3. опять удаляем в базе все ачивки и делаем `reset` - новые ачивки больше не приходят

**Comment by morr** [comment]
- [ ] https://shikimori.org/comments/3825670

**Comment by morr** [comment]
- [ ] ещё баг. у человека World_Houp 9 "длиннотайтлов" просмотренных https://monosnap.com/file/dpOJHaj57dbe8pyrukwDopjZO1Gols но у него есть ачивка longshounen https://monosnap.com/file/kCBo6vH0273i8a50ZDFYZOwBuQ7W9V

**Comment by morr** [comment]
- [ ] https://shikimori.org/achievements/genre/mahou_shoujo у пользователя user_id=3824 92 аниме, подходящих под ачивку, в списке. а для ачивки надо 94. при этом прогресс по ачивке у него 4%

и я вчера проверял эту штуку
на только что локально запущенном neko воспроизвести не смог
такое ощущение, что ломается через какое-то времся работы
